apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi3
  labels:
    app.kubernetes.io/name: taxi3
    app.kubernetes.io/version: 0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi3
      app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: taxi3
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
      - name: taxi3
        image: quay.io/keithchong/taxi:v1.0.0
        imagePullPolicy: Always
        volumeMounts:
        - name: web-files
          mountPath: /usr/share/booktaxi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      volumes:
      - name: web-files
        configMap:
          name: www-files
      imagePullSecrets:
        - name: kmcdermo-pull-secret
